<?php

/**
 * Implements hook_preprocess_html().
 */
function layout_body_class_preprocess_html(&$variables) {
  // Get the current layout.
  $layout = layout_get_layout();
  
  // Check if a layout is active.
  if (!empty($layout['name'])) {
    // Add the layout machine name as a class to the body tag.
    $variables['classes_array'][] = 'layout-' . drupal_clean_css_identifier($layout['name']);
  }
}
